services:
  fastapi-app:
    build: .
    volumes:
      - ./fastapi-app:/myapp
    ports:
      - "3001:${FASTAPI_PORT}"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi-app
